config/routes.rb
Rails.application.routes.draw do

  # 管理者
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"

  }

  # ユーザー
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者側
  namespace :admin do
    get '/' => 'dashboards#index'
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :update]
    resources :groups, only: [:index, :destroy]
    resources :posts, only: [:show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
  end

  # ユーザー側
  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'

    # ゲストログイン
    devise_scope :user do
      post 'users/guest_sign_in', to: 'sessions#guest_sign_in'
    end

    #投稿
    resources :posts do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    # マイページ名前パス
    get 'users/mypage' => 'users#show', as: 'mypage'
   
    # ユーザー
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'

      resources :favorites, only: [:index]

      member do
        #退会確認_名前パス
        get 'confirm_withdraw'
      end

      resources :bikes
    end

    #検索(ransack仕様)
    get 'search' => 'searches#index', as: 'search'

    #マップ
    get '/map' => 'posts#map', as: 'map'

    #グループ
    resources :groups do
      resources :group_users, only: [:create, :edit, :update, :destroy]
      resources :group_posts, only: [:create, :destroy]
      resource :event_notices, only: [:new, :create]
      get "event_notices/sent" => "event_notices#sent", as: "sent"
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="bg-dark text-white py-4 mt-auto">
  <div class="container text-center">
    <p class="mb-0 small text-secondary"><i class="fas fa-bicycle"></i>Bike_app</p>
    <div class="admin-link">
      <% unless admin_signed_in? %>
        <%= link_to new_admin_session_path, class: "text-secondary", style: "text-decoration: none; opacity: 0.2;" do %>
          <i class="fas fa-cog"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BikeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/8e86ac478f.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="d-flex flex-column min-vh-100">
      <div class="sticky-top" style="z-index: 1050;">
        <header>
          <nav class="navbar navbar-expand-lg navbar-dark shadow-sm" style="background-color: <%= admin_signed_in? ? '#FF8C00' : '#212529' %>;">
            <div class="container">
              <%= link_to (admin_signed_in? ? admin_path : root_path), class: "navbar-brand" do %>
                <%= image_tag 'bike-app_logo.png', size: '80x80', class: "d-inline-block align-top" %>
              <% end %>
              
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                  <% if admin_signed_in? %>
                    <li class="nav-item"><%= link_to "ダッシュボード", admin_path,  class: "nav-link" %></li>
                    <li class="nav-item"><%= link_to 'グループ一覧', admin_groups_path, class: 'nav-link' %></li>
                    <li class="nav-item"><%= link_to "ユーザー一覧", admin_users_path, class: "nav-link" %></li>
                    <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :get, class: "nav-link" %></li>
                  
                  <% elsif user_signed_in? %>
                    <li class="nav-item"><%= link_to "マイページ", mypage_path, class: "nav-link" %></li>
                    <li class="nav-item"><%= link_to "ルートマップ", map_path, class: "nav-link" %></li>
                    <li class="nav-item"><%= link_to 'グループ', groups_path, class: 'nav-link' %></li>
                    <li class="nav-item"><%= link_to "ユーザー一覧", users_path, class: "nav-link" %>
                    <li class="nav-item"><%= link_to "投稿一覧", posts_path, class: "nav-link" %></li>
                    <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
                    <li class="nav-item"><%= link_to "ログアウト", destroy_user_session_path,  class: "nav-link" %></li>
                    
                  <% else %>
                    <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
                    <li class="nav-item"><%= link_to "新規登録", new_user_registration_path, class: "nav-link" %></li>
                    <li class="nav-item"><%= link_to "ログイン", new_user_session_path, class: "nav-link" %></li>
                    <li class="nav-item"><%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post, class: "nav-link text-info fw-bold" %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          </nav>
        </header>
        <% if user_signed_in? %>
          <div class="search_form text-center py-3 bg-light">
            <%= form_with url: search_path, local: true, method: :get do |f| %>
              <% #検索ワード入力 %>
              <%= f.text_field :word, placeholder: "キーワードを入力" %>
              
              <%= f.select :range, options_for_select([['ユーザー', 'User'], ['投稿', 'Post']]) %>
              
              <%= f.submit "検索", class: "btn btn-primary btn-sm" %>
            <% end %>
          </div>
        <% end %>
        <% flash.each do |key, message| %>
          <% alert_class = (key == 'notice') ? 'success' : 'danger' %>
          <div class="alert alert-<%= alert_class %> m-0 rounded-0 border-0 text-center shadow-sm" style="padding: 10px 0; font-weight: bold; font-size: 0.9rem;">
            <%= message %>
          </div>
        <% end %>
      </div>
      <main>
        <%= yield %>
      </main>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>